"""Add datasetname column to writer

Revision ID: 040e86c62aba
Revises: 213aa70cb694
Create Date: 2020-04-04 17:11:21.146961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040e86c62aba'
down_revision = '213aa70cb694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('write', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datasetname', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('write', schema=None) as batch_op:
        batch_op.drop_column('datasetname')

    # ### end Alembic commands ###
