"""'add_correlate'

Revision ID: 213aa70cb694
Revises: 70894db03e8b
Create Date: 2020-03-27 15:49:22.957529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213aa70cb694'
down_revision = '70894db03e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correlate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['filterproxy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('correlate')
    # ### end Alembic commands ###
