"""add parametric channel

Revision ID: 70894db03e8b
Revises: f09aee631071
Create Date: 2020-03-18 15:57:23.674324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70894db03e8b'
down_revision = 'f09aee631071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logicalchannel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parametric_chan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('parmetric_chan', 'logicalchannel', ['parametric_chan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logicalchannel', schema=None) as batch_op:
        batch_op.drop_constraint('parametric_chan', type_='foreignkey')
        batch_op.drop_column('parametric_chan_id')

    # ### end Alembic commands ###
