"""Add generator output

Revision ID: f09aee631071
Revises: dc9546bb9eb1
Create Date: 2020-02-06 13:55:06.857648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f09aee631071'
down_revision = 'dc9546bb9eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generator', schema=None) as batch_op:
            batch_op.add_column(sa.Column('output', sa.Boolean(), nullable=True))
    with op.batch_alter_table('generator', schema=None) as batch_op:
            op.execute("""
            UPDATE generator
            SET output = true
            """) # set all previously undefined output values to True

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generator', schema=None) as batch_op:
        batch_op.drop_column('output')

    # ### end Alembic commands ###
